### ISSUE TITLE
I want help

### ISSUE THREAD

**Issue by 12ohit** [alessandrojean/tachi-local#2]
I wanted to create and deploy aniyomi-local but I am very noob in this stuff I am unable to deploy the fork I made of this repository on Netlify. Can you help me deploy it? If yes please DM me on Discord 12ohit#1563 because your DM's are closed.

**Comment by 12ohit** [comment]
Nevermind, I realised that your latest commit was making the problem so I used the repository from before that commit and it worked.

**Comment by alessandrojean** [comment]
Hi, 12ohit, sorry about not replying it before. 

Glad to hear you managed to make it build with success 😄 

Any new questions or issues you find, feel free to open a new issue or PR with fixes!

**Comment by alessandrojean** [comment]
Also, @12ohit, please replace my Google Analytics tag on `index.html` with a custom one created by you to your fork or remove that script from the page, please.

**Comment by 12ohit** [comment]
Ok I will remove that Google Analytics tag, thanks
