### ISSUE TITLE
Add a "Prefer English title" toggle

### ISSUE THREAD

**Issue by 12ohit** [alessandrojean/tachi-local#3]
* A switch button that says prefer English title:
   If set true will set the English title by default and only if the English title is not available will fall back to the Romaji title and if set false will just set the Romaji title.

***
Question:
![image](https://user-images.githubusercontent.com/53574579/183298504-a19f5fdd-9265-4d7d-a69a-5b3c8bd14598.png)
* Is it possible to make the input field not save the history? Happens for `Animation Studios` and `Genres`.

**Comment by alessandrojean** [comment]
> Is it possible to make the input field not save the history? Happens for Animation Studios and Genres.

Yes, you're looking for the `autocomplete` attribute.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#disabling_autocompletion

About the suggestion, it's doable, will try to work on it when I have some free time.

**Comment by 12ohit** [comment]
Thanks so much, I appreciate your help

**Comment by 12ohit** [comment]
![image](https://user-images.githubusercontent.com/53574579/201721100-b0198144-349a-43b2-97f0-f1f93af6557c.png)
---
![image](https://user-images.githubusercontent.com/53574579/201722873-86814480-e41c-4f46-aaee-373a2e2fc72e.png)

I was thinking to add a preference panel there and in that keep two switches, one for title preference and other for include of cover image with download, preferences are saved in local storage, I tried implementing it on my own but I have 0 experience with Vue's Composition API😔, just thought I will put what I had in mind here

Also I know you are using headlessUI but I am no able to style their Switches so I gave up on doing this on my own

**Comment by alessandrojean** [comment]
I am planning to do soon a major rewrite of the tool to drop all the usages of Bulma in favour of TailwindCSS. When I get to that I will also likely add the preference too so you can just update your fork with the changes and do some minor adjustments.

**Comment by 12ohit** [comment]
Oh great, sure then I will wait for your update, thanks a bunch✌️

**Comment by alessandrojean** [comment]
Closed in d01464f. There are a lot of changes, so do the merging in your fork with attention.

The save cover button issue will be addressed soon.

**Comment by 12ohit** [comment]
> Closed in [d01464f](https://github.com/alessandrojean/tachi-local/commit/d01464f7b7681312f3924c9f6f27459e3d919c99). There are a lot of changes, so do the merging in your fork with attention.

Got it, thanks😄
